<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>CertificateEngine</RootNamespace>
    <AssemblyName>CertificateEngine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Cors and base JSON are built-in to .NET 6 -->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.0" />
    <PackageReference Include="PuppeteerSharp" Version="6.0.0" />
  </ItemGroup>

</Project>
